
name: 'Execução N1'


on:
    workflow_dispatch:


jobs:
    e2e-testes:
        runs-on: ['ubuntu-latest']
        steps: 
            - uses: actions/checkout@v4
            - name: instalando Yarn
              run: npm install -g yarn

            - name: instalando dependências Yarn 
              run: yarn
            
            - name: instalando cypress
              run: npm install cypress 
                   npm install cypress-mochawesome-reporter


            - name: Executando os testes 
              run:  npx cypress run --reporter cypress-mochawesome-reporter --reporter-options reportDir=cypress/reports,overwrite=false,html=false,json=true

            - name: Relatórios dos testes
              uses: actions/upload-artifact@v3
              if: ${{ !cancelled() }}
              with:
                name: Relatório Testes E2E
                path: cypress/reports